{% set name = "ervmancer" %}
{% set version = "0.1.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  no_git_env_vars: True
  noarch: python
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-deps"
  entry_points:
    - ervrmancer = ervmancer.main:main

requirements:
  channels:
    - conda-forge
    - bioconda
    - defaults
  host:
    - python >=3.8
    - setuptools>=1.4.0
    - pip
  run:
    - python >=3.8
    - bowtie2
    - samtools
    - bedtools
    - numpy
    - pandas
    - tqdm
    - regex

test:
  commands:
    - ervmancer --help

about:
  home: https://github.com/AuslanderLab/ervmancer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'ERV identification tool using bowtie2, samtools, and bedtools'
  description: |
    ervmancer is a tool for identifying and analyzing HERVs in genomic data using a pipeline of bowtie2 for alignment, samtools for processing,
    and bedtools.
  doc_url: https://github.com/AuslanderLab/ervmancer
  dev_url: https://github.com/AuslanderLab/ervmancer

extra:
  recipe-maintainers:
    - bryantduong